# Generated by Django 4.2.7 on 2025-08-03 13:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name="Ім'я гостя")),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон гостя')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='Email гостя')),
                ('appointment_date', models.DateField(verbose_name='Дата запису')),
                ('appointment_time', models.TimeField(verbose_name='Час запису')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('in_progress', 'В роботі'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна вартість')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='Бали лояльності')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокований')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('description', models.TextField(verbose_name='Опис послуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ціна')),
                ('duration', models.IntegerField(verbose_name='Тривалість (хвилини)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='STOInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва СТО')),
                ('description', models.TextField(verbose_name='Опис')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Робочі години')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Інформація про СТО',
                'verbose_name_plural': 'Інформація про СТО',
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершення')),
                ('mechanic_notes', models.TextField(blank=True, verbose_name='Примітки механіка')),
                ('actual_duration', models.IntegerField(verbose_name='Фактична тривалість (хвилини)')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фінальна вартість')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.appointment', verbose_name='Запис')),
            ],
            options={
                'verbose_name': 'Історія обслуговування',
                'verbose_name_plural': 'Історія обслуговування',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Зароблено'), ('spent', 'Витрачено')], max_length=10, verbose_name='Тип транзакції')),
                ('points', models.IntegerField(verbose_name='Кількість балів')),
                ('description', models.CharField(max_length=200, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Транзакція лояльності',
                'verbose_name_plural': 'Транзакції лояльності',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer', verbose_name='Клієнт'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service', verbose_name='Послуга'),
        ),
    ]
