# Generated by Django 5.2.4 on 2025-08-03 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, verbose_name='Опис категорії')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок відображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категорія послуг',
                'verbose_name_plural': 'Категорії послуг',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category__order', 'category__name', 'name'], 'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.servicecategory', verbose_name='Категорія'),
        ),
    ]
