# Generated by Django 5.2.4 on 2025-08-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoinfo',
            name='what_you_can_item1',
            field=models.CharField(default='Ознайомитися з переліком послуг та цінами', max_length=300, verbose_name='Пункт 1'),
        ),
        migrations.AddField(
            model_name='stoinfo',
            name='what_you_can_item2',
            field=models.CharField(default='Записатися на обслуговування онлайн', max_length=300, verbose_name='Пункт 2'),
        ),
        migrations.AddField(
            model_name='stoinfo',
            name='what_you_can_title',
            field=models.CharField(default='У нас ви можете:', max_length=200, verbose_name='Заголовок розділу "Що ви можете"'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='stoinfo',
            name='motto',
            field=models.CharField(max_length=200, verbose_name='Девіз'),
        ),
        migrations.AlterField(
            model_name='stoinfo',
            name='welcome_text',
            field=models.TextField(verbose_name='Привітальний текст'),
        ),
    ]
