# Generated by Django 5.2.4 on 2025-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stoinfo_what_you_can_item1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoinfo',
            name='what_you_can_item1',
        ),
        migrations.RemoveField(
            model_name='stoinfo',
            name='what_you_can_item2',
        ),
        migrations.AddField(
            model_name='stoinfo',
            name='what_you_can_items',
            field=models.JSONField(default=list, help_text='Список пунктів у форматі JSON', verbose_name='Пункти "Що ви можете"'),
        ),
    ]
