# Generated by Django 5.2.4 on 2025-08-05 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_stoinfo_what_you_can_item1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва боксу')),
                ('description', models.TextField(blank=True, verbose_name='Опис боксу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('working_hours', models.JSONField(default=dict, help_text='Графік роботи у форматі JSON: {"monday": {"start": "08:00", "end": "18:00"}, ...}', verbose_name='Графік роботи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Бокси',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.box', verbose_name='Бокс'),
        ),
    ]
