# Generated by Django 4.2.7 on 2025-08-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_service_duration_remove_service_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('in_progress', 'В роботі'), ('completed', 'Завершено'), ('cancelled', 'Скасовано клієнтом'), ('cancelled_by_admin', 'Скасовано адміністратором')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
