# Generated by Django 4.2.7 on 2025-08-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
