# Generated by Django 5.2.4 on 2025-08-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Опис боксу (англ.)'),
        ),
        migrations.AddField(
            model_name='box',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва боксу (англ.)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Опис послуги (англ.)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва послуги (англ.)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Опис категорії (англ.)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва категорії (англ.)'),
        ),
        migrations.AddField(
            model_name='stoinfo',
            name='address_en',
            field=models.TextField(blank=True, verbose_name='Адреса (англ.)'),
        ),
        migrations.AddField(
            model_name='stoinfo',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Опис (англ.)'),
        ),
        migrations.AddField(
            model_name='stoinfo',
            name='email_en',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (англ.)'),
        ),
        migrations.AddField(
            model_name='stoinfo',
            name='motto_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Девіз (англ.)'),
        ),
        migrations.AddField(
            model_name='stoinfo',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва СТО (англ.)'),
        ),
        migrations.AddField(
            model_name='stoinfo',
            name='phone_en',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон (англ.)'),
        ),
        migrations.AddField(
            model_name='stoinfo',
            name='welcome_text_en',
            field=models.TextField(blank=True, verbose_name='Привітальний текст (англ.)'),
        ),
        migrations.AddField(
            model_name='stoinfo',
            name='what_you_can_items_en',
            field=models.JSONField(blank=True, default=list, help_text='Список пунктів англійською у форматі JSON', verbose_name='Пункти "Що ви можете" (англ.)'),
        ),
        migrations.AddField(
            model_name='stoinfo',
            name='what_you_can_title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок розділу "Що ви можете" (англ.)'),
        ),
        migrations.AddField(
            model_name='stoinfo',
            name='working_hours_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Робочі години (англ.)'),
        ),
    ]
