# Generated by Django 5.2.4 on 2025-08-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_box_description_en_box_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='is_active',
        ),
    ]
